"""empty message

Revision ID: e5543133f731
Revises: 
Create Date: 2024-03-11 18:09:58.431019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5543133f731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('followed_users', sa.Integer(), nullable=False),
    sa.Column('users_following_me', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('type', sa.Enum('nature', 'party', 'culture', 'relax', 'family', 'sport', name='type_enum'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('place', sa.String(length=240), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=750), nullable=False),
    sa.Column('language', sa.Enum('spanish', 'catalan', 'english', 'german', 'french', name='language_enum'), nullable=True),
    sa.Column('gender', sa.Enum('female_only', 'queer_only', 'all_genders', name='gender_enum'), nullable=False),
    sa.Column('price_type', sa.Enum('free', 'paid', name='pricetype_enum'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_people', sa.Integer(), nullable=True),
    sa.Column('max_people', sa.Integer(), nullable=True),
    sa.Column('lgtbi', sa.Boolean(), nullable=True),
    sa.Column('pet_friendly', sa.Boolean(), nullable=False),
    sa.Column('kid_friendly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('max_age >= min_age', name='event_max_age_greater_than_min_age'),
    sa.CheckConstraint('max_people >= min_people', name='event_max_people_greater_than_min_people'),
    sa.CheckConstraint('min_age >= 0', name='event_min_age_positive'),
    sa.CheckConstraint('min_people >= 0', name='event_min_people_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_kid_friendly'), ['kid_friendly'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_lgtbi'), ['lgtbi'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_max_age'), ['max_age'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_max_people'), ['max_people'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_min_age'), ['min_age'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_min_people'), ['min_people'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_pet_friendly'), ['pet_friendly'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_place'), ['place'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_price_type'), ['price_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)

    op.create_table('favorite_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signedup_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signedup_event')
    op.drop_table('favorite_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_price_type'))
        batch_op.drop_index(batch_op.f('ix_event_price'))
        batch_op.drop_index(batch_op.f('ix_event_place'))
        batch_op.drop_index(batch_op.f('ix_event_pet_friendly'))
        batch_op.drop_index(batch_op.f('ix_event_name'))
        batch_op.drop_index(batch_op.f('ix_event_min_people'))
        batch_op.drop_index(batch_op.f('ix_event_min_age'))
        batch_op.drop_index(batch_op.f('ix_event_max_people'))
        batch_op.drop_index(batch_op.f('ix_event_max_age'))
        batch_op.drop_index(batch_op.f('ix_event_lgtbi'))
        batch_op.drop_index(batch_op.f('ix_event_language'))
        batch_op.drop_index(batch_op.f('ix_event_kid_friendly'))
        batch_op.drop_index(batch_op.f('ix_event_gender'))
        batch_op.drop_index(batch_op.f('ix_event_duration'))
        batch_op.drop_index(batch_op.f('ix_event_date'))

    op.drop_table('event')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
